import type { Meeting } from "./model";

export const DEMO_CARLETON_MEETINGS: Meeting[] = [
  // --- Fall 2026 ---
  {
    id: "demo-comp-1405-lec",
    institutionId: "carleton",
    courseCode: "DEMO 1001",
    nativeSection: "A",
    nativeComponentType: "LEC",
    courseName: "Sample computing class",
    termLabel: "Fall 2026",
    days: ["MO", "WE"],
    startTime: "10:05",
    endTime: "11:25",
    startDate: "2026-09-09",
    endDate: "2026-12-09",
    location: {
      kind: "physical",
      nativeText: "TB",
      buildingId: "tory-building",
      room: "208",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-24T12:00:00.000Z" },
  },
  {
    id: "demo-comp-1405-tut",
    institutionId: "carleton",
    courseCode: "DEMO 1001",
    nativeSection: "A1",
    nativeComponentType: "TUT",
    courseName: "Sample computing class",
    termLabel: "Fall 2026",
    days: ["FR"],
    startTime: "11:35",
    endTime: "12:55",
    startDate: "2026-09-09",
    endDate: "2026-12-09",
    location: {
      kind: "physical",
      nativeText: "HP",
      buildingId: "herzberg-laboratories",
      room: "4115",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-24T12:00:00.000Z" },
  },
  {
    id: "demo-busi-1004-lec",
    institutionId: "carleton",
    courseCode: "DEMO 1002",
    nativeSection: "A",
    nativeComponentType: "LEC",
    courseName: "Sample business class",
    termLabel: "Fall 2026",
    days: ["MO", "WE"],
    startTime: "14:35",
    endTime: "15:55",
    startDate: "2026-09-09",
    endDate: "2026-12-09",
    location: {
      kind: "physical",
      nativeText: "DT",
      buildingId: "dunton-tower",
      room: "2203",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-24T12:00:00.000Z" },
  },
  {
    id: "demo-math-1007-lec",
    institutionId: "carleton",
    courseCode: "DEMO 1003",
    nativeSection: "B",
    nativeComponentType: "LEC",
    courseName: "Sample mathematics class",
    termLabel: "Fall 2026",
    days: ["TU", "TH"],
    startTime: "13:05",
    endTime: "14:25",
    startDate: "2026-09-09",
    endDate: "2026-12-09",
    location: {
      kind: "physical",
      nativeText: "SA",
      buildingId: "southam-hall",
      room: "TH-B",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-24T12:00:00.000Z" },
  },
  {
    id: "demo-math-1007-tut",
    institutionId: "carleton",
    courseCode: "DEMO 1003",
    nativeSection: "B1",
    nativeComponentType: "TUT",
    courseName: "Sample mathematics class",
    termLabel: "Fall 2026",
    days: ["TH"],
    startTime: "15:35",
    endTime: "16:25",
    startDate: "2026-09-09",
    endDate: "2026-12-09",
    location: {
      kind: "physical",
      nativeText: "PA",
      buildingId: "paterson-hall",
      room: "133",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-24T12:00:00.000Z" },
  },
  {
    id: "demo-sysc-2004-lec",
    institutionId: "carleton",
    courseCode: "DEMO 1004",
    nativeSection: "A",
    nativeComponentType: "LEC",
    courseName: "Sample engineering class",
    termLabel: "Fall 2026",
    days: ["TU", "TH"],
    startTime: "10:05",
    endTime: "11:25",
    startDate: "2026-09-09",
    endDate: "2026-12-09",
    location: {
      kind: "physical",
      nativeText: "ME",
      buildingId: "mackenzie-building",
      room: "3356",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-24T12:00:00.000Z" },
  },
  {
    id: "demo-sysc-2004-lab",
    institutionId: "carleton",
    courseCode: "DEMO 1004",
    nativeSection: "A1",
    nativeComponentType: "LAB",
    courseName: "Sample engineering class",
    termLabel: "Fall 2026",
    days: ["TU"],
    startTime: "14:35",
    endTime: "16:25",
    startDate: "2026-09-09",
    endDate: "2026-12-09",
    location: {
      kind: "physical",
      nativeText: "CB",
      buildingId: "canal-building",
      room: "2202",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-24T12:00:00.000Z" },
  },

  // --- Winter 2027 ---
  {
    id: "demo-comp-2401-lec",
    institutionId: "carleton",
    courseCode: "DEMO 2001",
    nativeSection: "A",
    nativeComponentType: "LEC",
    courseName: "Sample systems programming class",
    termLabel: "Winter 2027",
    days: ["MO", "WE"],
    startTime: "08:35",
    endTime: "09:55",
    startDate: "2027-01-06",
    endDate: "2027-04-07",
    location: {
      kind: "physical",
      nativeText: "CB",
      buildingId: "canal-building",
      room: "3101",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-24T12:00:00.000Z" },
  },
  {
    id: "demo-busi-2001-lec",
    institutionId: "carleton",
    courseCode: "DEMO 2002",
    nativeSection: "B",
    nativeComponentType: "LEC",
    courseName: "Sample management class",
    termLabel: "Winter 2027",
    days: ["MO", "WE"],
    startTime: "11:35",
    endTime: "12:55",
    startDate: "2027-01-06",
    endDate: "2027-04-07",
    location: {
      kind: "physical",
      nativeText: "DT",
      buildingId: "dunton-tower",
      room: "2017",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-24T12:00:00.000Z" },
  },
  {
    id: "demo-comm-1001-lec",
    institutionId: "carleton",
    courseCode: "DEMO 2003",
    nativeSection: "A",
    nativeComponentType: "LEC",
    courseName: "Sample communication class",
    termLabel: "Winter 2027",
    days: ["TU", "TH"],
    startTime: "10:05",
    endTime: "11:25",
    startDate: "2027-01-06",
    endDate: "2027-04-07",
    location: {
      kind: "physical",
      nativeText: "PK",
      buildingId: "pigiarvik",
      room: "608",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-24T12:00:00.000Z" },
  },
  {
    id: "demo-elec-1001-lab",
    institutionId: "carleton",
    courseCode: "DEMO 2004",
    nativeSection: "L1",
    nativeComponentType: "LAB",
    courseName: "Sample circuits lab",
    termLabel: "Winter 2027",
    days: ["TU", "TH"],
    startTime: "13:05",
    endTime: "14:25",
    startDate: "2027-01-06",
    endDate: "2027-04-07",
    location: {
      kind: "physical",
      nativeText: "TT",
      buildingId: "carleton-technology-training-centre",
      room: "402",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-24T12:00:00.000Z" },
  },
  {
    id: "demo-math-2007-lec",
    institutionId: "carleton",
    courseCode: "DEMO 2005",
    nativeSection: "A",
    nativeComponentType: "LEC",
    courseName: "Sample multivariable calculus",
    termLabel: "Winter 2027",
    days: ["FR"],
    startTime: "10:05",
    endTime: "11:25",
    startDate: "2027-01-06",
    endDate: "2027-04-07",
    location: {
      kind: "physical",
      nativeText: "TB",
      buildingId: "tory-building",
      room: "360",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-24T12:00:00.000Z" },
  },
];
