import type { Meeting } from "../common/model";

export const DEMO_BROCK_MEETINGS: Meeting[] = [
  // --- Fall 2026 ---
  {
    id: "demo-brock-cosc1p02-lec",
    institutionId: "brock",
    courseCode: "COSC 1P02",
    nativeSection: "01",
    nativeComponentType: "LEC",
    courseName: "Introduction to Computer Science",
    termLabel: "Fall 2026",
    days: ["MO", "WE"],
    startTime: "09:30",
    endTime: "11:00",
    startDate: "2026-09-08",
    endDate: "2026-12-08",
    location: {
      kind: "physical",
      nativeText: "ST 107",
      buildingId: "arthur-schmon-tower",
      room: "107",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-26T12:00:00.000Z" },
  },
  {
    id: "demo-brock-math1p66-lec",
    institutionId: "brock",
    courseCode: "MATH 1P66",
    nativeSection: "01",
    nativeComponentType: "LEC",
    courseName: "Mathematical Reasoning",
    termLabel: "Fall 2026",
    days: ["MO", "WE", "FR"],
    startTime: "12:00",
    endTime: "13:00",
    startDate: "2026-09-08",
    endDate: "2026-12-08",
    location: {
      kind: "physical",
      nativeText: "TH 247",
      buildingId: "thistle-complex",
      room: "247",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-26T12:00:00.000Z" },
  },
  {
    id: "demo-brock-actg1p91-lec",
    institutionId: "brock",
    courseCode: "ACTG 1P91",
    nativeSection: "01",
    nativeComponentType: "LEC",
    courseName: "Principles of Financial Accounting",
    termLabel: "Fall 2026",
    days: ["TU", "TH"],
    startTime: "14:00",
    endTime: "15:30",
    startDate: "2026-09-08",
    endDate: "2026-12-08",
    location: {
      kind: "physical",
      nativeText: "GSB 308",
      buildingId: "goodman-school-business",
      room: "308",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-26T12:00:00.000Z" },
  },
  // --- Winter 2027 ---
  {
    id: "demo-brock-cosc1p03-lec",
    institutionId: "brock",
    courseCode: "COSC 1P03",
    nativeSection: "01",
    nativeComponentType: "LEC",
    courseName: "Introduction to Data Structures",
    termLabel: "Winter 2027",
    days: ["MO", "WE"],
    startTime: "10:00",
    endTime: "11:30",
    startDate: "2027-01-06",
    endDate: "2027-04-09",
    location: {
      kind: "physical",
      nativeText: "MC H313",
      buildingId: "mackenzie-chown-complex",
      room: "H313",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-26T12:00:00.000Z" },
  },
  {
    id: "demo-brock-biol1p92-lec",
    institutionId: "brock",
    courseCode: "BIOL 1P92",
    nativeSection: "01",
    nativeComponentType: "LEC",
    courseName: "Diversity of Life",
    termLabel: "Winter 2027",
    days: ["TU", "TH"],
    startTime: "11:30",
    endTime: "13:00",
    startDate: "2027-01-06",
    endDate: "2027-04-09",
    location: {
      kind: "physical",
      nativeText: "CFHBRC 201",
      buildingId: "cairns-complex",
      room: "201",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-26T12:00:00.000Z" },
  },
];
