import type { Meeting } from "../common/model";

export const DEMO_YORK_MEETINGS: Meeting[] = [
  // --- Fall 2026 ---
  {
    id: "demo-york-eecs1022-lec",
    institutionId: "york",
    courseCode: "EECS 1022",
    nativeSection: "A",
    nativeComponentType: "LEC",
    courseName: "Programming for Mobile Computing",
    termLabel: "Fall 2026",
    days: ["MO", "WE", "FR"],
    startTime: "10:30",
    endTime: "11:30",
    startDate: "2026-09-09",
    endDate: "2026-12-09",
    location: {
      kind: "physical",
      nativeText: "LAS 1005",
      buildingId: "lassonde-building",
      room: "1005",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-26T12:00:00.000Z" },
  },
  {
    id: "demo-york-math1013-lec",
    institutionId: "york",
    courseCode: "MATH 1013",
    nativeSection: "A",
    nativeComponentType: "LEC",
    courseName: "Applied Calculus I",
    termLabel: "Fall 2026",
    days: ["MO", "WE", "FR"],
    startTime: "12:30",
    endTime: "13:30",
    startDate: "2026-09-09",
    endDate: "2026-12-09",
    location: {
      kind: "physical",
      nativeText: "CLH A",
      buildingId: "curtis-lecture-halls",
      room: "A",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-26T12:00:00.000Z" },
  },
  {
    id: "demo-york-eecs1022-lab",
    institutionId: "york",
    courseCode: "EECS 1022",
    nativeSection: "LAB 01",
    nativeComponentType: "LAB",
    courseName: "Programming for Mobile Computing Lab",
    termLabel: "Fall 2026",
    days: ["TU"],
    startTime: "14:00",
    endTime: "16:00",
    startDate: "2026-09-09",
    endDate: "2026-12-09",
    location: {
      kind: "physical",
      nativeText: "BRG 217",
      buildingId: "bergeron-centre",
      room: "217",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-26T12:00:00.000Z" },
  },
  {
    id: "demo-york-eng1000-lec",
    institutionId: "york",
    courseCode: "ENG 1000",
    nativeSection: "M",
    nativeComponentType: "LEC",
    courseName: "Engineering Design",
    termLabel: "Fall 2026",
    days: ["TU", "TH"],
    startTime: "10:00",
    endTime: "11:30",
    startDate: "2026-09-09",
    endDate: "2026-12-09",
    location: {
      kind: "physical",
      nativeText: "DB 0014",
      buildingId: "dahdaleh-building",
      room: "0014",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-26T12:00:00.000Z" },
  },
  {
    id: "demo-york-psyc1010-lec",
    institutionId: "york",
    courseCode: "PSYC 1010",
    nativeSection: "A",
    nativeComponentType: "LEC",
    courseName: "Introduction to Psychology",
    termLabel: "Fall 2026",
    days: ["TU", "TH"],
    startTime: "13:00",
    endTime: "14:30",
    startDate: "2026-09-09",
    endDate: "2026-12-09",
    location: {
      kind: "physical",
      nativeText: "VH A",
      buildingId: "vari-hall",
      room: "A",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-26T12:00:00.000Z" },
  },
];
