import type { Meeting } from "../common/model";

export const DEMO_LAURIER_MEETINGS: Meeting[] = [
  // --- Fall 2026 ---
  {
    id: "demo-laurier-cp104-lec",
    institutionId: "laurier",
    courseCode: "CP 104",
    nativeSection: "A",
    nativeComponentType: "LEC",
    courseName: "Introduction to Programming",
    termLabel: "Fall 2026",
    days: ["MO", "WE", "FR"],
    startTime: "09:30",
    endTime: "10:20",
    startDate: "2026-09-08",
    endDate: "2026-12-08",
    location: {
      kind: "physical",
      nativeText: "LH 1001",
      buildingId: "lazaridis-hall",
      room: "1001",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-24T12:00:00.000Z" },
  },
  {
    id: "demo-laurier-bu111-lec",
    institutionId: "laurier",
    courseCode: "BU 111",
    nativeSection: "B",
    nativeComponentType: "LEC",
    courseName: "Understanding the Business Environment",
    termLabel: "Fall 2026",
    days: ["MO", "WE"],
    startTime: "11:30",
    endTime: "12:50",
    startDate: "2026-09-08",
    endDate: "2026-12-08",
    location: {
      kind: "physical",
      nativeText: "P 1005",
      buildingId: "peters-building",
      room: "1005",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-24T12:00:00.000Z" },
  },
  {
    id: "demo-laurier-ma103-lec",
    institutionId: "laurier",
    courseCode: "MA 103",
    nativeSection: "A",
    nativeComponentType: "LEC",
    courseName: "Calculus I",
    termLabel: "Fall 2026",
    days: ["TU", "TH"],
    startTime: "10:00",
    endTime: "11:20",
    startDate: "2026-09-08",
    endDate: "2026-12-08",
    location: {
      kind: "physical",
      nativeText: "SC 101",
      buildingId: "science-building",
      room: "101",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-24T12:00:00.000Z" },
  },
  {
    id: "demo-laurier-ec120-lec",
    institutionId: "laurier",
    courseCode: "EC 120",
    nativeSection: "A",
    nativeComponentType: "LEC",
    courseName: "Introduction to Microeconomics",
    termLabel: "Fall 2026",
    days: ["TU", "TH"],
    startTime: "13:00",
    endTime: "14:20",
    startDate: "2026-09-08",
    endDate: "2026-12-08",
    location: {
      kind: "physical",
      nativeText: "S 1002",
      buildingId: "schlegel-building",
      room: "1002",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-24T12:00:00.000Z" },
  },
  {
    id: "demo-laurier-cp104-lab",
    institutionId: "laurier",
    courseCode: "CP 104",
    nativeSection: "L1",
    nativeComponentType: "LAB",
    courseName: "Programming Lab",
    termLabel: "Fall 2026",
    days: ["FR"],
    startTime: "13:30",
    endTime: "15:20",
    startDate: "2026-09-08",
    endDate: "2026-12-08",
    location: {
      kind: "physical",
      nativeText: "BA 110",
      buildingId: "bricker-academic",
      room: "110",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-24T12:00:00.000Z" },
  },
];
