import type { Meeting } from "../common/model";

export const DEMO_MCMASTER_MEETINGS: Meeting[] = [
  // --- Fall 2026 ---
  {
    id: "demo-mac-compsci1md3-lec",
    institutionId: "mcmaster",
    courseCode: "COMPSCI 1MD3",
    nativeSection: "C01",
    nativeComponentType: "LEC",
    courseName: "Introduction to Programming",
    termLabel: "Fall 2026",
    days: ["MO", "WE", "TH"],
    startTime: "09:30",
    endTime: "10:20",
    startDate: "2026-09-08",
    endDate: "2026-12-08",
    location: {
      kind: "physical",
      nativeText: "BSB 147",
      buildingId: "burke-science-building",
      room: "147",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-26T12:00:00.000Z" },
  },
  {
    id: "demo-mac-math1za3-lec",
    institutionId: "mcmaster",
    courseCode: "MATH 1ZA3",
    nativeSection: "C01",
    nativeComponentType: "LEC",
    courseName: "Engineering Mathematics I",
    termLabel: "Fall 2026",
    days: ["MO", "WE", "TH"],
    startTime: "11:30",
    endTime: "12:20",
    startDate: "2026-09-08",
    endDate: "2026-12-08",
    location: {
      kind: "physical",
      nativeText: "JHE 264",
      buildingId: "john-hodgins-engineering",
      room: "264",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-26T12:00:00.000Z" },
  },
  {
    id: "demo-mac-eng1p13-lec",
    institutionId: "mcmaster",
    courseCode: "ENGINEER 1P13",
    nativeSection: "C01",
    nativeComponentType: "LEC",
    courseName: "Integrated Cornerstone Design Projects in Engineering",
    termLabel: "Fall 2026",
    days: ["TU", "FR"],
    startTime: "10:30",
    endTime: "11:20",
    startDate: "2026-09-08",
    endDate: "2026-12-08",
    location: {
      kind: "physical",
      nativeText: "ETB 125",
      buildingId: "engineering-technology-building",
      room: "125",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-26T12:00:00.000Z" },
  },
  {
    id: "demo-mac-eng1p13-lab",
    institutionId: "mcmaster",
    courseCode: "ENGINEER 1P13",
    nativeSection: "L02",
    nativeComponentType: "LAB",
    courseName: "Engineering Design Lab",
    termLabel: "Fall 2026",
    days: ["TU"],
    startTime: "14:30",
    endTime: "17:20",
    startDate: "2026-09-08",
    endDate: "2026-12-08",
    location: {
      kind: "physical",
      nativeText: "GHC 110",
      buildingId: "gerald-hatch-centre",
      room: "110",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-26T12:00:00.000Z" },
  },
  {
    id: "demo-mac-physics1a03-lec",
    institutionId: "mcmaster",
    courseCode: "PHYSICS 1A03",
    nativeSection: "C01",
    nativeComponentType: "LEC",
    courseName: "Introductory Physics",
    termLabel: "Fall 2026",
    days: ["TU", "TH"],
    startTime: "12:30",
    endTime: "13:20",
    startDate: "2026-09-08",
    endDate: "2026-12-08",
    location: {
      kind: "physical",
      nativeText: "ABB 102",
      buildingId: "arthur-bourns-building",
      room: "102",
    },
    source: { kind: "sample-timetable", recordedAt: "2026-09-26T12:00:00.000Z" },
  },
];
